[platformio]
default_envs = tramtrace

[env:tramtrace]
platform = espressif32
board = esp32dev
framework = arduino
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.3
    bblanchon/ArduinoJson@^6.21.5
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=1

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_flags =
    -std=c++17
    -I include
